name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y libhwloc-dev
    # make sure to explicitely checkout git submodule
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: configure
      run: mkdir build_openmp && cd build_openmp && cmake -DEULER_KOKKOS_BUILD=ON -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_HWLOC=ON ..
    - name: make
      run: cd build_openmp && make
